FROM nginx:alpine

COPY . /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["/bin/sh", "-c", "sed \"s|__API_URL__|${API_URL}|g\" /usr/share/nginx/html/app.js > /tmp/app.js && mv /tmp/app.js /usr/share/nginx/html/app.js && nginx -g 'daemon off;'"]
